services:
  backend: 
    build:
      context: ./backend
    image: mi-backendgastos-python
    container_name: backend-python
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.9:3306/lucymar_db
      SPRING_DATASOURCE_USERNAME: lucymar_user
      SPRING_DATASOURCE_PASSWORD: Admin
    networks:
      - red-gastos2

  frontend:
    build:
      context: ./frontend
    image: mi-frontendgastos-vue2
    container_name: frontend-vue2
    ports:
      - "8081:80"
    networks:
      - red-gastos2


networks:
  red-gastos2:
    driver: bridge

